services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=https://wonderquest.ajitm.com
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_SERVER_URL=https://wonderquest.ajitm.com
        - VITE_APP_FIREBASE_AUTH_API_KEY=AIzaSyBUXzuHWGi4vHXzN2CDSvqn6iJmPagCCvw
        - VITE_APP_FIREBASE_AUTH_DOMAIN=auto-kanban.firebaseapp.com
        - VITE_APP_FIREBASE_AUTH_PROJECT_ID=auto-kanban
        - VITE_APP_FIREBASE_AUTH_STORAGE_BUCKET=auto-kanban.appspot.com
        - VITE_APP_FIREBASE_AUTH_MESSAGING_SENDER_ID=769788129508
        - VITE_APP_FIREBASE_AUTH_APP_ID=1:769788129508:web:1237f78c8d61131110bcf1
        - VITE_APP_FIREBASE_AUTH_MEASUREMENT_ID=G-1234567890
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt  
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
