services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=https://[YOUR DOMAIN]
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_SERVER_URL=https:[YOUR DOMAIN]
        - VITE_APP_FIREBASE_AUTH_API_KEY=<your-firebase-auth-api-key>
        - VITE_APP_FIREBASE_AUTH_DOMAIN=<your-firebase-auth-domain>
        - VITE_APP_FIREBASE_AUTH_PROJECT_ID=<your-firebase-auth-domain>
        - VITE_APP_FIREBASE_AUTH_STORAGE_BUCKET=<your-firebase-auth-domain>
        - VITE_APP_FIREBASE_AUTH_MESSAGING_SENDER_ID=<your-firebase-auth-domain>
        - VITE_APP_FIREBASE_AUTH_APP_ID=<your-firebase-auth-domain>
        - VITE_APP_FIREBASE_AUTH_MEASUREMENT_ID=<your-firebase-auth-domain>
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt  
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
